### ISSUE TITLE
simpleLightbox is not a function

### ISSUE THREAD

**Issue by kiligir** [worldanvil/worldanvil-bug-tracker#1184]
**World Anvil Username**: kiligir

**World / Campaign / RPG Character / Manuscript Title**: Enos

**Feature**: Basic Website Functionality

**Related URLS** (To public & visible pages add screenshots otherwise): https://www.worldanvil.com/w/enos-kiligir/c/alliances-and-places-category

**Describe the Issue**
The console is logging the error

```js
Uncaught TypeError: $(...).simpleLightbox is not a function
    at HTMLDocument.<anonymous> (display.js?v=016535:124:521)
    at j (jquery.min.js:2:29999)
    at k (jquery.min.js:2:30313)
    at i (phidias.js:2:470858)```

any time the page is loaded. This breaks functionality on most objects on the page that should link.

**Comment by kiligir** [comment]
No idea what the function error is, but it has nothing to do with what was preventing the page from loading (was missing a starting [row] tag). Closing.
